### ISSUE TITLE
Reader continues scanning even after stopping

### ISSUE THREAD

**Issue by agordeev** [yannickl/QRCodeReader.swift#127]
Here's how I get result from the reader:

    func reader(_ reader: QRCodeReaderViewController, didScanResult result: QRCodeReaderResult) {
        reader.stopScanning()

        // my code goes here
    }

However, I'm getting 2 calls of the method above in a row. It's because `stopScanning` method stops scanning asynchronously.

```
  public func stopScanning() {
    if session.isRunning {
      sessionQueue.async {
        self.session.stopRunning()
      }
    }
  }
```

What was the reason to make it async? Is it safe to remove async from that method?

**Comment by yannickl** [comment]
Hi @agordeev,

I've added that by following the Apple example. The reader initialisation, start/stop scan is really heavy so this is better to manage that in background.

I've updated the code, it should be ok now.

**Comment by imran87** [comment]
Thanks for such a good contribution but very sorry to mention here stopScanning is still not working after find qr code.

reader.didFindCode = { result in
        
        self.reader.stopScanning()
      print("Completion with result: \(result.value) of type \(result.metadataType)")
    }

print line is called many time

**Comment by XFactorus** [comment]
Same for me, didScanResult is called at least twice, what is not good for app and I have to prevent it somehow manually (version 8.0.4, stopScanning called)

**Comment by yannickl** [comment]
Sorry for the inconvenience, I've made an update it should works now.

**Comment by Ingibjorg** [comment]
@yannickl thank you! This fix is not included in your latest version 8.0.4. Can you please publish a new version with this fix?

**Comment by yannickl** [comment]
@Ingibjorg sorry for the inconvenience. I was waiting for feedback to be sure it fixes the problem and more important, that it not produced new ones.

I'm going to push it in a new **minor** version, not a patch one.

**Comment by Ingibjorg** [comment]
Thanks @yannickl. I tested your fix and I can confirm that it's working in my app. I no longer see duplicated scans.

**Comment by yannickl** [comment]
@Ingibjorg the `8.1.0` version is released!

**Comment by khoanpase61742** [comment]
The bug still appears on `8.1.0` &` 8.2.0` version.

**Comment by yannickl** [comment]
@khoanpase61742 are you able to make this issue happen in a reproducible way? It could help me to debug it.

**Comment by khoanpase61742** [comment]
@yannickl I use QR Code's value as key to get data from server using Alamofire. When callback is called, it'll be called Twice
```
func reader(_ reader: QRCodeReaderViewController, didScanResult result: QRCodeReaderResult) {
  reader.stopScanning()

   dismiss(animated: true) { [weak self] in
       // When I apply Alamofire here, the block code inside completion of Alamofire is called TWICE
    }
}
```

**Comment by yannickl** [comment]
@khoanpase61742 it is called twice everytime? Because the completion block of the dismiss method is called once for me.

**Comment by khoanpase61742** [comment]
@yannickl The first call everything is ok, then the second call will crash application.

```
func reader(_ reader: QRCodeReaderViewController, didScanResult result: QRCodeReaderResult) {
  reader.stopScanning()

   dismiss(animated: true) { [weak self] in
        print("Outside Alamofire's completion block code") // This line is called only once
       
       // When I apply Alamofire here, the block code inside completion of Alamofire is called TWICE
       getResult(key: "123"){ result in
              print("Inside Alamofire's completion block code + \(result)" ) // This line is called at least twice, the second call will crash application because `result` is nil.
       }
    }
}
```    
 ```
func getResult(key: String, completion: @escaping (_ result: Result?) -> ()){
        let url:String = BASE_URL + "getResult?key=\(key)"
        
        Alamofire.request(url)
            .responseObject { (response: DataResponse<Result>) in
                switch response.result {
                case .success:
                    let result = response.result.value
                    if result != nil {
                        completion(result!)
                    }
                    completion(nil)
                case .failure(let error):
                    print(error)
                    completion(nil)
                }
        }
    }
```
